name: Build
on:
  push:
    branches: main
jobs:
  build-bindings:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Get Electron Version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'package.json'
          prop_path: 'electronVersion'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # https://github.com/nodejs/node-gyp/issues/1663#issuecomment-535049449
    - name: Patch node gyp on Windows to support Visual Studio 2019
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
    - name: Update NPM Client
      run: npm install -g npm
    - name: Install and Rebuild Bindings
      run: npm install
    - name: Move Bindings To Repo
      run: node process.js ${{ steps.version.outputs.prop }} ${{ secrets.TOKEN }} ${{ secrets.EMAIL }}
